title: AI course
tagline: Deep Learning Lecture

author:
  name: Michael Hotaling
  url: MichaelHotaling.github.io

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme

paginate: 5

tags_path: /tags/
categories_path: /categories/

remote_theme: zivong/jekyll-theme-hydure
